//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyR.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlyR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Only R Application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ACCESSIBILITY_ONLY_R {
            get {
                return ResourceManager.GetString("ACCESSIBILITY_ONLY_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string APP_VER {
            get {
                return ResourceManager.GetString("APP_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back to main page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BACK_TO_MAIN_PAGE {
            get {
                return ResourceManager.GetString("BACK_TO_MAIN_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files copied に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string COPIED {
            get {
                return ResourceManager.GetString("COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not create folder {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CREATE_FOLDER_ERROR {
            get {
                return ResourceManager.GetString("CREATE_FOLDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not start recording に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR_START {
            get {
                return ResourceManager.GetString("ERROR_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not stop recording に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR_STOP {
            get {
                return ResourceManager.GetString("ERROR_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insufficient free space to record に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string INSUFFICIENT_FREE_SPACE {
            get {
                return ResourceManager.GetString("INSUFFICIENT_FREE_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No limit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LIFE_0 {
            get {
                return ResourceManager.GetString("LIFE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 Day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LIFE_1_DAY {
            get {
                return ResourceManager.GetString("LIFE_1_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 Month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LIFE_1_MONTH {
            get {
                return ResourceManager.GetString("LIFE_1_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 Week に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LIFE_1_WEEK {
            get {
                return ResourceManager.GetString("LIFE_1_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 Year に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LIFE_1_YR {
            get {
                return ResourceManager.GetString("LIFE_1_YR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 Days に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LIFE_2_DAYS {
            get {
                return ResourceManager.GetString("LIFE_2_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 Months に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LIFE_2_MONTHS {
            get {
                return ResourceManager.GetString("LIFE_2_MONTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 Weeks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LIFE_2_WEEKS {
            get {
                return ResourceManager.GetString("LIFE_2_WEEKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 Years に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LIFE_2_YRS {
            get {
                return ResourceManager.GetString("LIFE_2_YRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6 Months に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LIFE_6_MONTHS {
            get {
                return ResourceManager.GetString("LIFE_6_MONTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mono に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MONO {
            get {
                return ResourceManager.GetString("MONO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No limit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NO_LIMIT {
            get {
                return ResourceManager.GetString("NO_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No recordings today! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NO_RECORDINGS {
            get {
                return ResourceManager.GetString("NO_RECORDINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No space on {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NO_SPACE {
            get {
                return ResourceManager.GetString("NO_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not recording に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NOT_RECORDING {
            get {
                return ResourceManager.GetString("NOT_RECORDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 hour に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ONE_HOUR {
            get {
                return ResourceManager.GetString("ONE_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 minute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ONE_MIN {
            get {
                return ResourceManager.GetString("ONE_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recording に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RECORDING {
            get {
                return ResourceManager.GetString("RECORDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recording salvaged from last session! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RECORDING_SALVAGED {
            get {
                return ResourceManager.GetString("RECORDING_SALVAGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recordings folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RECORDINGS_FOLDER_TOOLTIP {
            get {
                return ResourceManager.GetString("RECORDINGS_FOLDER_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please restart OnlyR after changing the language. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RESTART_LANGUAGE {
            get {
                return ResourceManager.GetString("RESTART_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save today&apos;s recordings to drive {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SAVE_TO_DRIVE {
            get {
                return ResourceManager.GetString("SAVE_TO_DRIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save today&apos;s recordings to drives {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SAVE_TO_DRIVES {
            get {
                return ResourceManager.GetString("SAVE_TO_DRIVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Recording Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SELECT_DEST_FOLDER {
            get {
                return ResourceManager.GetString("SELECT_DEST_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow close when recording に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_ALLOW_CLOSE {
            get {
                return ResourceManager.GetString("SETTINGS_ALLOW_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always on top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_ALWAYS_ON_TOP {
            get {
                return ResourceManager.GetString("SETTINGS_ALWAYS_ON_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto restart after silence detected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_AUTORESTART_AFTER_SILENCE {
            get {
                return ResourceManager.GetString("SETTINGS_AUTORESTART_AFTER_SILENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bit rate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_BIT_RATE {
            get {
                return ResourceManager.GetString("SETTINGS_BIT_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Channels に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_CHANNELS {
            get {
                return ResourceManager.GetString("SETTINGS_CHANNELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fade out recordings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_FADE_OUT {
            get {
                return ResourceManager.GetString("SETTINGS_FADE_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Genre (in MP3 tag) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_GENRE {
            get {
                return ResourceManager.GetString("SETTINGS_GENRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use loopback capture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_LOOPBACK_CAPTURE {
            get {
                return ResourceManager.GetString("SETTINGS_LOOPBACK_CAPTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max recording time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_MAX_RECORDING_TIME {
            get {
                return ResourceManager.GetString("SETTINGS_MAX_RECORDING_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recording device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_RECORDING_DEVICE {
            get {
                return ResourceManager.GetString("SETTINGS_RECORDING_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recording lifetime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_RECORDING_LIFETIME {
            get {
                return ResourceManager.GetString("SETTINGS_RECORDING_LIFETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recordings... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_RECORDINGS_BTN {
            get {
                return ResourceManager.GetString("SETTINGS_RECORDINGS_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recordings folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_RECORDINGS_FOLDER {
            get {
                return ResourceManager.GetString("SETTINGS_RECORDINGS_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample rate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_SAMPLE_RATE {
            get {
                return ResourceManager.GetString("SETTINGS_SAMPLE_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop recording after period of silence に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_SILENCE_PERIOD {
            get {
                return ResourceManager.GetString("SETTINGS_SILENCE_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chunk detection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_SPLIT_RECORDING_BY_CHUNK {
            get {
                return ResourceManager.GetString("SETTINGS_SPLIT_RECORDING_BY_CHUNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start minimised に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_START_MINIMIZED {
            get {
                return ResourceManager.GetString("SETTINGS_START_MINIMIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start recording on launch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_START_ON_LAUNCH {
            get {
                return ResourceManager.GetString("SETTINGS_START_ON_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop on a period of silence に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_STOP_RECORDING_ON_SILENCE {
            get {
                return ResourceManager.GetString("SETTINGS_STOP_RECORDING_ON_SILENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop after Silence に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_STOP_SILENCE {
            get {
                return ResourceManager.GetString("SETTINGS_STOP_SILENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chunk detection span [ms] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_CHUNK_DETECTION_SPAN {
            get {
                return ResourceManager.GetString("SETTINGS_CHUNK_DETECTION_SPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SETTINGS_TOOLTIP {
            get {
                return ResourceManager.GetString("SETTINGS_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speech に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SPEECH {
            get {
                return ResourceManager.GetString("SPEECH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start recording に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string START_RECORDING_TOOLTIP {
            get {
                return ResourceManager.GetString("START_RECORDING_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stereo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STEREO {
            get {
                return ResourceManager.GetString("STEREO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STOP_ON_SILENCE_DISABLED {
            get {
                return ResourceManager.GetString("STOP_ON_SILENCE_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop recording に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STOP_RECORDING_TOOLTIP {
            get {
                return ResourceManager.GetString("STOP_RECORDING_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopping に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STOPPING {
            get {
                return ResourceManager.GetString("STOPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown error! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UNKNOWN_COPY_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_COPY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VIEW に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VIEW {
            get {
                return ResourceManager.GetString("VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} hours に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string X_HOURS {
            get {
                return ResourceManager.GetString("X_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} minutes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string X_MINS {
            get {
                return ResourceManager.GetString("X_MINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} seconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string X_SECONDS {
            get {
                return ResourceManager.GetString("X_SECONDS", resourceCulture);
            }
        }
    }
}
